services:
  utr-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: true_evaluation
      POSTGRES_USER: w41k4z
      POSTGRES_PASSWORD: w41k4z
    ports:
      - "5432:5432"